### ISSUE TITLE
repo code structure

### ISSUE THREAD

**Issue by yunjunz** [opera-adt/sentinel1-burst-id#2]
I propose we use the `src/{module_name}` code structure, following the packaging practice. Then we could use `s1_burst_id` as a python module in other repos. What do you think @hfattahi @vbrancat @LiangJYu ?

```bash
/sentinel1-burst-id
   /bin
      create_burst_id.py
   /src
      /s1_burst_id
         __inti__.py
         BurstDataFrame.py
         query.py
         upload_data.py
```

**Comment by hfattahi** [comment]
Sounds good to me.
