### ISSUE TITLE
burst ID syntax

### ISSUE THREAD

**Issue by yunjunz** [opera-adt/sentinel1-burst-id#6]
The current syntax for the unique burst ID is `t{trackNum}s{subSwathNum}b{burstNum}`. How about changing it to the following?

```
T{trackNum}{acquisitionMode}{subSwathNum}B{burstNum}
```

where `{acquisitionMode}` can be `IW` (by default), `EW`, `WV` and `SM` (https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes). Since the mode string is upper case, we could use upper case for `T` and `B` as well; or all lower case also works.

We should use the same syntax in https://github.com/opera-adt/sentinel1-reader/pull/1.

**Comment by LiangJYu** [comment]
Assuming file naming convention is consistent across all modes, then this is automatically accounted for [here](https://github.com/opera-adt/sentinel1-reader/blob/074190c12b6b8a858ed1fc8474dc8a491bf80c37/src/sentinel1_reader/sentinel1_reader.py#L277). Removing `iw` [here](https://github.com/opera-adt/sentinel1-reader/blob/074190c12b6b8a858ed1fc8474dc8a491bf80c37/src/sentinel1_reader/sentinel1_reader.py#L408) and in the comments would also be required.

**Comment by yunjunz** [comment]
The current burst ID calculation depends on the duration of each burst, thus, I don't think it's applicable to other Sentinel-1 modes. Saying that, the current unique burst ID syntax is perfectly fine. Close this issue.
